// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-central-1",
    "aws_cognito_identity_pool_id": "eu-central-1:6f897dc7-6714-49e5-a984-daa5fcb0d93e",
    "aws_cognito_region": "eu-central-1",
    "aws_user_pools_id": "eu-central-1_BkQ5c0e7E",
    "aws_user_pools_web_client_id": "5bi31nb0411f1hib69847s709j",
    "oauth": {}
};


export default awsmobile;
